export const ROUTES = {
  AI_CHAT: '/api/chat',
  AI_ANALYZE_MARKET: '/api/analyze-market',
  CLAUDE_CHAT: '/api/claude/chat',
  CLAUDE_ANALYZE_MARKET: '/api/claude/analyze-market',
  TRADE_BOT: '/api/trade-bot',
  SIGN_UP: '/api/auth/signup',
  SIGN_IN: '/api/auth/signin',
  SIGN_IN_EMAIL: '/api/auth/signin-email',
  SWITCH_MODE: '/api/auth/switch-mode',
  SIGN_OUT: '/api/auth/signout',
  ME: '/api/auth/me',
  USER_INFO: '/api/user-info',
  USER_STREAM: '/api/user-stream',
  FUTURES_ORDER: '/api/futures/order',
  FUTURES_TAKE_PROFIT: '/api/futures/take-profit',
  FUTURES_STOP_LOSS: '/api/futures/stop-loss',
  FUTURES_CANCEL_ORDER: '/api/futures/cancel',
  FUTURES_POSITIONS: '/api/futures/positions',
  FUTURES_OPEN_ORDERS: '/api/futures/open-orders',
  FUTURES_PENDING_TP_SL: '/api/futures/pending-tpsl',
  FUTURES_CLOSE_POSITION: '/api/futures/close-position',
  FUTURES_CANCEL_TPSL: '/api/futures/cancel-tpsl',
  FUTURES_LEVERAGE_BRACKET: '/api/futures/leverage-bracket',
  FUTURES_COMMISSION_RATE: '/api/futures/commission-rate',
};
